title: Download Canon Printer Driver | Setup Wireless Canon Printer 
description: Canon com ijsetup - To get the canon printer driver software for your printer model separately transfer to Canon com ijsetup page after entering your webpage, type the name & number of your printer in the search function and click on the search button.
